version: 0.0
os: linux
files:
  - source: ./rainbow-b2/
    destination: /opt/Artifacts
permissions:
    owner: root
    group: root
    type:
      - file
      - directory
hooks:
  ApplicationStart:
    - location: deploy-scripts/ApplicationStart.sh
      timeout: 300
    - echo "APllication start"
