version: 0.0
os: linux

files:
  - source: /
    destination: /opt/Artifacts

permissions:
  - object: /opt/Artifacts/deploy-scripts
    pattern: '**'
    mode: '0777'
    owner: root
    group: root
    type:
      - file
      - directory
  
hooks:
  BeforeInstall:
    - location: deploy-scripts/backup.sh
  ApplicationStart:
    - location: deploy-scripts/ApplicationStart.sh
  
