version: 0.2
env:
  variables:
     dev_env: "QA" 

  parameter-store:
     JDBClass: "/jdbc/default/driverClassName"
     JDBCUrl: "/jdbc/default/url"
     JDBCUser: "/jdbc/default/username"
     JDBCPassword: "/jdbc/default/password"
     
  secrets-manager:
   #   qa_rds_cluster: "$Environment/rainbowcred:qa_rds_cluster"
      ec2hostname: "$Environment/rainbowcred:ec2hostname"
  exported-variables:
     - ec2hostname
  #  - bash gitcommands.sh

phases:  
  pre_build:
    commands:
        - echo "My env is $Environment"
        - echo Nothing to do in the pre_build phase...
    
  build:
    commands:
       - echo Build started on 'date'
       - echo "$ec2hostname"
       


     
  post_build:
    commands:
        - |
          if [[ "$Environment" == "QA" ]] || [[if "$Environment" == "Prod"]]; then 
           echo "if condition working" 
           echo "$ec2hostname"
          fi   

    finally:
      - echo This is the finally block execution!
artifacts:
  files:
    - 'Artifacts/*'
    - appspec.yml
    - 'deploy-scripts/*'
