version: 0.2
phases:
  install:

    commands:
      
  pre_build:
    commands:
     
  build:
    commands:
     
    finally:
      - echo This is the finally block execution!
artifacts:
  files:
    - 'Artifacts/**/*'
    - appspec.yml
    - 'deploy-scripts/**/*'
