version: 0.2
env:
  variables:
     dev_env: "QA"

  parameter-store:
     JDBClass: "/jdbc/default/driverClassName"
     JDBCUrl: "/jdbc/default/url"
     JDBCUser: "/jdbc/default/username"
     JDBCPassword: "/jdbc/default/password"
     
  secrets-manager:
    HTS_MHSReg: $Environment/rainbowcred:hts.myhearst.services.region
    HTS_MHSEnv: $Environment/rainbowcred:hts.myhearst.services.environment
phases:  
  pre_build:
    commands:
  #      - CURRENT_ENV=`echo $CODEBUILD_INITIATOR | cut -d '-' -f2 | tr '[:upper:]' '[:lower:]'`
        - echo "My env is $Environment"
        - echo Nothing to do in the pre_build phase...
    
  build:
    commands:
       - echo Build started on 'date'


     
  post_build:
    commands:
      
       if [ $Environment == "QA" ]; then
          echo "if condition working"
       fi    
      - sed -i "s/HTS_MHSReg/$HTS_MHSReg/g" env.properties
      - sed -i "s/HTS_MHSEnv/$HTS_MHSEnv/g" env.properties
      - sed -i "s/JDBClass/$JDBClass/g" env.properties  
      - sed -i "s/JDBCUser/$JDBCUser/g" env.properties
      - sed -i "s/JDBCPassword/$JDBCPassword/g" env.properties
      - tail -25 env.properties
      - mv env.properties Artifacts/
      
    finally:
      - echo This is the finally block execution!
artifacts:
  files:
    - 'Artifacts/*'
    - appspec.yml
    - 'deploy-scripts/*'
