version: 0.2
env:
  parameter-store:
     JDBClass: "/jdbc/default/driverClassName"
     JDBCUrl: "/jdbc/default/url"
     JDBCUser: "/jdbc/default/username"
     JDBCPassword: "/jdbc/default/password"
phases:  
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
       - echo Build started on 'date'
     
  post_build:
    commands:
      - echo $JDBCUrl
      - echo $JDBCUser
      - echo $JDBClass
      - echo $JDBCPassword
      - sed -i "s/JDBClass/$JDBClass/g" env.properties
   #   - sed -i "s/JDBCUrl/$JDBCUrl/g" env.properties
      - sed -i "s/JDBCUser/$JDBCUser/g" env.properties
      - sed -i "s/JDBCPassword/$JDBCPassword/g" env.properties
      - tail -25 env.properties
      - mv env.properties Artifacts/
      
    finally:
      - echo This is the finally block execution!
artifacts:
  files:
    - 'Artifacts/*'
    - appspec.yml
    - 'deploy-scripts/*'
