version: 0.2
env:
  parameter-store:
     JDBClass: dev/JDBC:driverClassName
     JDBCUrl: dev/JDBC:url
     JDBCUser: dev/JDBC:username
     JDBCPassword: dev/JDBC:Password
phases:  
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
       - echo Build started on 'date'
     
  post_build:
    commands:
     post_build:
    commands:
      - echo $JDBCUser
      - cp env.properties /opt/rainbow-v1/env.properties
      - sed -i "s/JDBCUser/$JDBCUser/g" env.properties
      - sed -i "s/JDBCPassword/$JDBCPassword/g" env.properties
      - tail env.properties
      - mv env.properties
      
    finally:
      - echo This is the finally block execution!
artifacts:
  files:
    - 'Artifacts/*'
    - appspec.yml
    - 'deploy-scripts/*'
