version: 0.2
env:
  variables:
     dev_env: "QA"

  parameter-store:
     JDBClass: "/jdbc/default/driverClassName"
     JDBCUrl: "/jdbc/default/url"
     JDBCUser: "/jdbc/default/username"
     JDBCPassword: "/jdbc/default/password"
     
  secrets-manager:
      qa_rds_cluster: "$Environment:QA/rainbowcred:qa_rds_cluster"
      ec2hostname: "$Environment:QA/rainbowcred:ec2hostname"
  exported-variables:
      - qa_rds_cluster
      - ec2hostname
phases:  
  pre_build:
    commands:
        - echo "My env is $Environment"
        - echo Nothing to do in the pre_build phase...
    
  build:
    commands:
       - echo Build started on 'date'


     
  post_build:
    commands:
        - |
          if [[ "$Environment" == "QA" ]] || [[if "$Environment" == "Prod"]]; then 
           echo "if condition working" 
          fi   

    finally:
      - echo This is the finally block execution!
artifacts:
  files:
    - 'Artifacts/*'
    - appspec.yml
    - 'deploy-scripts/*'
