version: 0.2
env:
  parameter-store:
     JDBClass: jdbc/default/driverClassName
     JDBCUrl: jdbc/default/url
     JDBCUser: jdbc/default/username
     JDBCPassword: jdbc/default/Password
phases:  
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
       - echo Build started on 'date'
     
  post_build:
    commands:
      - echo $JDBCUser
      - cp env.properties /opt/rainbow-v1/env.properties
      - sed -i "s/JDBCUser/$JDBCUser/g" env.properties
      - sed -i "s/JDBCPassword/$JDBCPassword/g" env.properties
      - tail env.properties
      - mv env.properties /opt/rainbow-v1
      
    finally:
      - echo This is the finally block execution!
artifacts:
  files:
    - 'Artifacts/*'
    - appspec.yml
    - 'deploy-scripts/*'
