version: 0.2
env:
  variables:
     dev_env: "dev"
  parameter-store:
     JDBClass: "/jdbc/default/driverClassName"
     JDBCUrl: "/jdbc/default/url"
     JDBCUser: "/jdbc/default/username"
     JDBCPassword: "/jdbc/default/password"
     
phases:  
  pre_build:
    commands:
  #      - CURRENT_ENV=`echo $CODEBUILD_INITIATOR | cut -d '-' -f2 | tr '[:upper:]' '[:lower:]'`
        - echo "My env is $Environment"
        - echo Nothing to do in the pre_build phase...
    
  build:
    commands:
       - echo Build started on 'date'


     
  post_build:
    commands:
      - echo $JDBCUrl
      - echo $JDBCUser
      - echo $JDBClass
      - echo $JDBCPassword
      - echo $HTS_MHSReg
      - echo $HTS_MHSEnv
      
      if [$Environment == "QA"]; then
          - sed -i "s/hts.myhearst.services.environment/$hts.myhearst.services.environment/g" env.properties
          - sed -i "s/hts.myhearst.services.environment/$hts.myhearst.services.environment/g" env.properties
      fi
      
      - sed -i "s/JDBClass/$JDBClass/g" env.properties
   #   - sed -i "s/JDBCUrl/$JDBCUrl/g" env.properties
      - sed -i "s/JDBCUser/$JDBCUser/g" env.properties
      - sed -i "s/JDBCPassword/$JDBCPassword/g" env.properties
      - tail -25 env.properties
      - mv env.properties Artifacts/
      
    finally:
      - echo This is the finally block execution!
artifacts:
  files:
    - 'Artifacts/*'
    - appspec.yml
    - 'deploy-scripts/*'
